"""Checking Migrations

Revision ID: 433948b4519d
Revises: 48a2f701a277
Create Date: 2025-09-05 17:32:48.774395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433948b4519d'
down_revision: Union[str, Sequence[str], None] = '48a2f701a277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('temp', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'temp')
    # ### end Alembic commands ###
