"""add position in playlist_games

Revision ID: 965e2d85a137
Revises: 172fac4d33fc
Create Date: 2025-09-05 17:58:57.124805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965e2d85a137'
down_revision: Union[str, Sequence[str], None] = '172fac4d33fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Step 1: add column as nullable
    op.add_column('playlist_games', sa.Column('position', sa.Integer(), nullable=True))

    # Step 2: backfill existing rows
    conn = op.get_bind()

    # fetch distinct playlist_ids
    playlists = conn.execute(sa.text("SELECT DISTINCT playlist_id FROM playlist_games")).fetchall()
    for (pid,) in playlists:
        rows = conn.execute(
            sa.text("SELECT game_id FROM playlist_games WHERE playlist_id = :pid"),
            {"pid": pid}
        ).fetchall()

        for idx, (gid,) in enumerate(rows):
            conn.execute(
                sa.text("""
                    UPDATE playlist_games
                    SET position = :pos
                    WHERE playlist_id = :pid AND game_id = :gid
                """),
                {"pos": idx, "pid": pid, "gid": gid}
            )

    # Step 3: enforce NOT NULL
    op.alter_column('playlist_games', 'position', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_games', 'position')
    # ### end Alembic commands ###
